services:
  - type: web
    name: mhada-payroll-portal
    runtime: node
    plan: free
    region: singapore
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
    autoDeploy: true
